### ISSUE TITLE
Set of geohashes returned for polygon with narrow sections does not cover the full polygon

### ISSUE THREAD

**Issue by mciethan** [Bonsanto/polygon-geohasher#16]
Hi! I have been using this library to convert administrative polygons into sets of geohashes. Before I describe my issue, I want to thank you for creating/contributing to this library - I am grateful that I don't have to write these kinds of functions from scratch for the work I'm doing!

I noticed that the set of level 7 geohashes I received for a polygon of the city of Boston, MA, omits a significant section of the city. The polygon is in blue, and the outline of the resulting level 7 geohashes is in orange.

![image](https://user-images.githubusercontent.com/84473423/190439339-32b5b5b2-b115-49b3-aa58-f437c57ae457.png)

I was wondering if the algorithm for converting polygons to geohashes is thrown off by the fact that there is a very narrow stretch of the polygon where it's possible that no level 7 geohashes fit. When I set inner=False, it worked as expected and gets me all the geohashes that cover the polygon. However, I would prefer to have the set of geohashes that are specifically within the polygon, even if there are no level 7 geohashes covering that one narrow stretch of polygon. In other words, it would be nice to have all geohashes within the polygon, even if they aren't all contiguous with other.

Attached below is a text file with the WKT string of the polygon I'm using, so that people can replicate the issue if needed. I am thinking of forking this repo and playing with the code myself once I have more time, so any response pointing out where the issues in the code the issue might be would be helpful. Even if other people don't have the capacity to debug this issue themselves, that would help me test some different approaches myself. I'll update this issue if I get the chance to work on this issue myself.

[boston_wkt.txt](https://github.com/Bonsanto/polygon-geohasher/files/9576568/boston_wkt.txt)

**Comment by mciethan** [comment]
Upon further review, my issue was with another part of my code not having to do with the polygon-geohasher library. Closing this issue!

**Comment by Bonsanto** [comment]
Thank you Ethan, I did not have to investigate it but thank you for closing
the ticket!
