### ISSUE TITLE
Convert a set of points into polygons and search

### ISSUE THREAD

**Issue by winash12** [Bonsanto/polygon-geohasher#2]
I have a set of points defined in terms of latitudes and longitudes. These are clustered on the surface of a sphere. Can I use your package to convert them into a polygon by constructing geohashes ?

Then I need to search for other points in that polygon using Shapely. Possible ?

**Comment by Bonsanto** [comment]
I am not sure if I understood your question. But you could use `python-geohash`, for instance:
```
import geohash
from polygon_geohasher.polygon_geohasher import geohashes_to_polygon
 
points = [(0, 0), (1, 1)]
geohashes = [geohash.encode(*p, precision=7) for p in points]
polygon = geohashes_to_polygon(geohashes)
```

**Comment by winash12** [comment]
Yes thanks @Bonsanto very neat approach.
